spring:
  application:
    name: telegram-auth
  datasource:
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}